places = ['henan','paris','newyork','ameri','shanghai']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=1))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=1)
print(places)
print(len(places))
places.append("tuerqi")
print(places)
places.remove('paris')
places.pop(-1)
places.insert(0,'o')
places[0] = places[0].title()
places[0] = places[0].lower()
places[0] = places[0].upper()

print(places)